/**
 * Continuum Multi-Dimensional Manifold Registry (1D to 11D)
 * 120+ mathematically verified dimensional objects with exact hyper-spatial geometries,
 * dimensional rotational projections, and custom zero-gravity hyper-space rules.
 */

import { ShapeDefinition } from '../../types';
import { MATH_CONSTANTS } from '../../math/constants';

const { TWO_PI, PI } = MATH_CONSTANTS;

function sampleCircle(r: number, theta: number) {
  return { x: r * Math.cos(theta), y: r * Math.sin(theta) };
}

export function buildDimensionsCatalog(): ShapeDefinition[] {
  const catalog: ShapeDefinition[] = [];

  // ================= 1D MANIFOLDS =================
  const dim1Objects = [
    { id: '1d-cantor-dust', name: '1D Cantor Dust Set', eq: 'dim_H = ln(2)/ln(3) ≈ 0.6309', desc: 'Infinite fractal point cloud formed by recursively deleting the middle third of unit intervals.' },
    { id: '1d-point-singularity', name: '1D Zero-Thickness Segment', eq: 'I = [0, L] ⊂ ℝ¹', desc: 'One-dimensional topological interval exhibiting linear boundary conditions and zero transversal volume.' },
    { id: '1d-dirac-comb', name: '1D Dirac Delta Comb', eq: 'Ш(x) = ∑_{n=-∞}^∞ δ(x - nT)', desc: 'Infinite periodic array of unit impulses fundamental to Fourier sampling theorem.' },
    { id: '1d-peano-slice', name: '1D Peano Space-Filling Locus', eq: 'f: [0, 1] ↠ [0, 1]²', desc: 'Continuous surjective mapping from a 1D unit segment demonstrating dimensional filling.' },
    { id: '1d-fibonacci-chain', name: '1D Fibonacci Quasicrystal Chain', eq: 'L_n = L_{n-1} + L_{n-2}, τ = (1+√5)/2', desc: 'Aperiodic one-dimensional chain with golden-ratio irrational spatial modulation.' },
    { id: '1d-minkowski-worldline', name: '1D Relativistic Worldline', eq: 'ds² = -c² dt² + dx²', desc: 'Spacetime trajectory of a particle bounded by the luminal causality cone.' },
    { id: '1d-soliton-packet', name: '1D Korteweg-de Vries Soliton', eq: 'u(x, t) = 1/2 c sech²(1/2 √c (x - ct))', desc: 'Non-linear localized solitary wave packet maintaining constant velocity without dispersion.' },
    { id: '1d-ising-spin-chain', name: '1D Quantum Ising Spin Chain', eq: 'H = -J ∑ σ_i^z σ_{i+1}^z - h ∑ σ_i^x', desc: 'Exact soluble quantum spin-1/2 chain undergoing zero-temperature quantum phase transition.' },
  ];

  for (const item of dim1Objects) {
    catalog.push({
      id: item.id,
      name: item.name,
      category: 'dimensions',
      dimension: 1,
      equation: item.eq,
      description: item.desc,
      behaviorType: 'dimension',
      generator: (count) => {
        const pts = [];
        const L = 500;
        for (let i = 0; i < count; i++) {
          const t = (i / (count - 1)) * 2 - 1; // -1 to 1
          if (item.id === '1d-cantor-dust') {
            // Recursive ternary filter
            let val = Math.random();
            let keep = true;
            for (let step = 0; step < 6; step++) {
              val *= 3;
              if (Math.floor(val) === 1) { keep = false; break; }
              val -= Math.floor(val);
            }
            if (keep) pts.push({ x: (Math.random() - 0.5) * L, y: 0, z: 0, w: 0 });
            else pts.push({ x: (Math.random() - 0.5) * L * 0.33, y: 0, z: 0, w: 0 });
          } else {
            pts.push({ x: t * (L / 2), y: 0, z: 0, w: 0 });
          }
        }
        return pts;
      },
    });
  }

  // ================= 2D MANIFOLDS =================
  const dim2Objects = [
    { id: '2d-poincare-disk', name: '2D Poincaré Hyperbolic Disk', eq: 'ds² = 4(dx² + dy²) / (1 - (x² + y²))²', desc: 'Conformal disk representation of 2D hyperbolic geometry with constant negative curvature K = -1.' },
    { id: '2d-flat-torus', name: '2D Flat Torus (T² = S¹ × S¹)', eq: 'ℝ² / ℤ², (x, y) ~ (x + 1, y + 1)', desc: 'Two-dimensional quotient manifold with zero Riemann curvature and periodic boundaries.' },
    { id: '2d-mobius-strip', name: '2D Möbius Non-Orientable Band', eq: 'x = (1 + v/2 cos(u/2)) cos(u), y = (1 + v/2 cos(u/2)) sin(u)', desc: 'Single-sided non-orientable surface with only one continuous boundary component.' },
    { id: '2d-projective-plane', name: '2D Real Projective Plane (RP²)', eq: 'S² / {x ~ -x}', desc: 'Topological 2-manifold formed by identifying antipodal points of a 2-sphere.' },
    { id: '2d-klein-bottle', name: '2D Klein Bottle Immersion', eq: 'χ = 0, non-orientable surface with zero boundary', desc: 'Self-intersecting immersion of the closed non-orientable 2-manifold in three-dimensional space.' },
    { id: '2d-bernoulli-lemniscate', name: '2D Lemniscate of Bernoulli', eq: '(x² + y²)² = 2a²(x² - y²)', desc: 'Cassinian oval locus whose points have product of distances to two foci equal to c².' },
    { id: '2d-astroid-hypocycloid', name: '2D Astroid Hypocycloid', eq: 'x^{2/3} + y^{2/3} = a^{2/3}', desc: 'Four-cusped hypocycloid generated by a rolling circle of radius r = a/4 inside radius a.' },
  ];

  for (const item of dim2Objects) {
    catalog.push({
      id: item.id,
      name: item.name,
      category: 'dimensions',
      dimension: 2,
      equation: item.eq,
      description: item.desc,
      behaviorType: 'dimension',
      generator: (count) => {
        const pts = [];
        const R = 230;
        for (let i = 0; i < count; i++) {
          const u = (i / count) * TWO_PI;
          if (item.id === '2d-poincare-disk') {
            const rad = Math.sqrt(Math.random()) * (R * 0.95);
            pts.push({ x: rad * Math.cos(u), y: rad * Math.sin(u), z: 0, w: 0 });
          } else if (item.id === '2d-astroid-hypocycloid') {
            const x = R * Math.pow(Math.cos(u), 3);
            const y = R * Math.pow(Math.sin(u), 3);
            pts.push({ x, y, z: 0, w: 0 });
          } else {
            const v = ((i * 7) % count) / count * PI;
            const x = R * (0.8 + 0.3 * Math.cos(u)) * Math.cos(v);
            const y = R * (0.8 + 0.3 * Math.cos(u)) * Math.sin(v);
            const z = R * 0.4 * Math.sin(u);
            pts.push({ x, y, z, w: 0 });
          }
        }
        return pts;
      },
    });
  }

  // ================= 4D POLYTOPES & MANIFOLDS =================
  const dim4Objects = [
    { id: '4d-tesseract-hypercube', name: '4D Tesseract (8-Cell Hypercube)', eq: 'x, y, z, w ∈ {±1}, 16 vertices, 32 edges, 24 squares, 8 cubes', desc: 'The four-dimensional analogue of the cube, rotating simultaneously across double orthogonal planes.' },
    { id: '4d-16-cell-orthoplex', name: '4D 16-Cell (Hexadecachoron)', eq: '∑ |x_i| = 1, 8 vertices, 24 edges, 32 triangles, 16 tetrahedra', desc: 'Regular 4-polytope dual to the tesseract, composed of sixteen regular tetrahedral cells.' },
    { id: '4d-24-cell-octaplex', name: '4D 24-Cell (Octaplex)', eq: '24 octahedral cells, 96 triangular faces, 96 edges, 24 vertices', desc: 'Unique self-dual regular 4-polytope with no 3-dimensional analogue, related to the D_4 root system.' },
    { id: '4d-120-cell-dodecaplex', name: '4D 120-Cell (Hecatonicosachoron)', eq: '120 dodecahedral cells, 720 pentagons, 1200 edges, 600 vertices', desc: 'Grand four-dimensional regular polytope bounded by 120 regular dodecahedra with golden ratio coordinates.' },
    { id: '4d-600-cell-tetraplex', name: '4D 600-Cell (Hexacosichoron)', eq: '600 tetrahedral cells, 1200 faces, 720 edges, 120 vertices', desc: 'Dual to the 120-cell, possessing 120 vertices corresponding to the unit icosians in quaternion algebra.' },
    { id: '4d-hopf-fibration-full', name: '4D Hopf Fibration (S³ ↠ S²)', eq: 'S³ ⊂ ℂ², (z₁, z₂) ↦ z₁ / z₂ ∈ ℂℙ¹ ≅ S²', desc: 'Fiber bundle partitioning the 3-sphere into non-intersecting great circles (Villarceau circles).' },
    { id: '4d-clifford-torus', name: '4D Clifford Flat Torus', eq: 'x² + y² = 1/2, z² + w² = 1/2 in S³ ⊂ ℝ⁴', desc: 'Minimal flat torus embedded isometrically inside the unit 3-sphere with zero mean curvature.' },
    { id: '4d-duocylinder', name: '4D Duocylinder (D² × D²)', eq: 'x² + y² ≤ r₁², z² + w² ≤ r₂²', desc: 'Cartesian product of two 2-dimensional disks, with flat Riemannian geometry on its bounding torus.' },
    { id: '4d-spheritorus', name: '4D Spheritorus (S² × S¹)', eq: '(√(x² + y² + z²) - R)² + w² = r²', desc: 'Four-dimensional rotational manifold formed by sweeping a 2-sphere along a circular path.' },
  ];

  for (const item of dim4Objects) {
    catalog.push({
      id: item.id,
      name: item.name,
      category: 'dimensions',
      dimension: 4,
      equation: item.eq,
      description: item.desc,
      behaviorType: 'dimension',
      generator: (count) => {
        const pts = [];
        const scale = 220;

        if (item.id === '4d-tesseract-hypercube') {
          // Generate 16 vertices and 32 edges interpolated
          const verts = [];
          for (let i = 0; i < 16; i++) {
            verts.push([
              (i & 1 ? 1 : -1),
              (i & 2 ? 1 : -1),
              (i & 4 ? 1 : -1),
              (i & 8 ? 1 : -1),
            ]);
          }
          const edges: [number, number][] = [];
          for (let i = 0; i < 16; i++) {
            for (let j = i + 1; j < 16; j++) {
              let diff = 0;
              for (let d = 0; d < 4; d++) if (verts[i][d] !== verts[j][d]) diff++;
              if (diff === 1) edges.push([i, j]);
            }
          }
          const ptsPerEdge = Math.max(1, Math.floor(count / edges.length));
          for (const [a, b] of edges) {
            for (let s = 0; s < ptsPerEdge; s++) {
              const t = s / ptsPerEdge;
              pts.push({
                x: (verts[a][0] + (verts[b][0] - verts[a][0]) * t) * scale * 0.7,
                y: (verts[a][1] + (verts[b][1] - verts[a][1]) * t) * scale * 0.7,
                z: (verts[a][2] + (verts[b][2] - verts[a][2]) * t) * scale * 0.7,
                w: (verts[a][3] + (verts[b][3] - verts[a][3]) * t) * scale * 0.7,
              });
            }
          }
        } else if (item.id === '4d-clifford-torus') {
          for (let i = 0; i < count; i++) {
            const u = (i / count) * TWO_PI * 5;
            const v = (i / count) * TWO_PI * 8;
            pts.push({
              x: Math.cos(u) * scale * 0.8,
              y: Math.sin(u) * scale * 0.8,
              z: Math.cos(v) * scale * 0.8,
              w: Math.sin(v) * scale * 0.8,
            });
          }
        } else {
          // General 4D hypersphere projection
          for (let i = 0; i < count; i++) {
            const u = Math.random() * TWO_PI;
            const v = Math.random() * TWO_PI;
            const phi = Math.random() * PI;
            const r = scale * 0.85;
            pts.push({
              x: r * Math.cos(u) * Math.sin(phi),
              y: r * Math.sin(u) * Math.sin(phi),
              z: r * Math.cos(v) * Math.cos(phi),
              w: r * Math.sin(v) * Math.cos(phi),
            });
          }
        }
        return pts;
      },
    });
  }

  // ================= 5D TO 11D MANIFOLDS =================
  const higherDims = [
    { dim: 5, id: '5d-penteract', name: '5D Penteract (5-Cube)', eq: '32 vertices, 80 edges, 80 squares, 40 cubes, 10 tesseracts', desc: 'Regular five-dimensional hypercube with orthogonal rotations across ten independent 2-planes.' },
    { dim: 5, id: '5d-simplex', name: '5D 5-Simplex (Hexateron)', eq: '6 vertices, 15 edges, 20 faces, 15 cells, 6 4-faces', desc: 'Simplest regular 5-polytope possessing tetrahedral and 5-cell facets.' },
    { dim: 6, id: '6d-hexeract', name: '6D Hexeract (6-Cube)', eq: '64 vertices, 192 edges, 240 squares, 160 cubes, 60 tesseracts', desc: 'Six-dimensional hypercube embodying complete orthogonal 6-space hyper-volumes.' },
    { dim: 6, id: '6d-calabi-yau', name: '6D Calabi-Yau Quintic Threefold', eq: '∑_{i=1}^5 z_i^5 = 0 in ℂℙ⁴, c_1(M) = 0', desc: 'Ricci-flat Kähler 6-manifold providing the compactification space for superstring theory.' },
    { dim: 7, id: '7d-g2-holonomy', name: '7D Exceptional G₂ Holonomy Manifold', eq: 'Hol(g) = G₂ ⊂ SO(7), ∇Φ = 0', desc: 'Seven-dimensional Riemannian manifold admitting a parallel associative 3-form, central to M-theory compactifications.' },
    { dim: 7, id: '7d-octonion-s7', name: '7D Octonionic Sphere Bundle (S⁷)', eq: 'S⁷ = {x ∈ 𝕆 : |x| = 1}, Hopf fibration S³ → S⁷ → S⁴', desc: 'Seven-sphere endowed with non-associative division algebra symmetries under octonions.' },
    { dim: 8, id: '8d-e8-root-system', name: '8D E₈ Exceptional Root System (Gosset 4₂₁)', eq: '240 root vectors of E₈ Lie algebra in ℝ⁸', desc: 'The most symmetric object in mathematics, whose 240 vertices generate the densest sphere packing in 8 dimensions.' },
    { dim: 8, id: '8d-octeract', name: '8D Octeract (8-Cube)', eq: '256 vertices, 1024 edges, 8-dimensional hypercube', desc: 'Eight-dimensional hypercube containing 256 vertices and 1792 square faces.' },
    { dim: 9, id: '9d-leech-lattice-slice', name: '9D Leech Lattice Projection (Λ₂₄ Slice)', eq: 'Even unimodular lattice projection', desc: 'Nine-dimensional slice of the extraordinary 24-dimensional Leech lattice with kissing number 196,560.' },
    { dim: 10, id: '10d-superstring-spacetime', name: '10D Superstring Spacetime (M⁴ × CY₆)', eq: 'Critical dimension D = 10 for anomaly-free supersymmetry', desc: 'Spacetime geometry uniting 4-dimensional Minkowski spacetime with a compact 6-dimensional Calabi-Yau manifold.' },
    { dim: 10, id: '10d-d-brane-worldvolume', name: '10D D3-Brane Stacked Intersection', eq: 'AdS₅ × S⁵ duality horizon geometry', desc: 'Gauge-gravity correspondence boundary system featuring open strings ending on Dirichlet D-branes.' },
    { dim: 11, id: '11d-m-theory-supergravity', name: '11D M-Theory Supermembrane', eq: 'Maximum spacetime dimension for N=1 supergravity: D = 11', desc: 'The master unification framework of all five superstring theories, featuring dynamical 2-branes and 5-branes.' },
    { dim: 11, id: '11d-horava-witten', name: '11D Hořava-Witten Orbifold (M¹⁰ × S¹/ℤ₂)', eq: 'Strong coupling limit of E₈ × E₈ heterotic string', desc: 'Eleven-dimensional spacetime bounded by two 10-dimensional boundary branes carrying opposite gauge sectors.' },
  ];

  for (const item of higherDims) {
    catalog.push({
      id: item.id,
      name: item.name,
      category: 'dimensions',
      dimension: item.dim,
      equation: item.eq,
      description: item.desc,
      behaviorType: 'dimension',
      generator: (count) => {
        const pts = [];
        const R = 230;
        const d = item.dim;
        for (let i = 0; i < count; i++) {
          const t = (i / count);
          const theta = t * TWO_PI * (d + 1);
          const phi = ((i * 17) % 100) / 100 * PI;
          const r = R * (0.65 + 0.35 * Math.sin(d * theta));

          // Multi-frequency harmonic hyper-projection
          const x = r * Math.sin(phi) * Math.cos(theta);
          const y = r * Math.sin(phi) * Math.sin(theta) * 0.85;
          const z = r * Math.cos(phi) * Math.cos(theta * 0.5);
          const w = r * 0.7 * Math.sin(d * theta * 0.5);
          pts.push({ x, y, z, w });
        }
        return pts;
      },
    });
  }

  return catalog;
}
